package net.legacyfabric.multifilament;

import net.fabricmc.filament.FilamentExtension;
import net.fabricmc.filament.task.CombineUnpickDefinitionsTask;
import net.fabricmc.filament.task.DownloadTask;
import net.fabricmc.filament.task.MapJarTask;
import net.fabricmc.filament.task.enigma.MapSpecializedMethodsTask;
import net.fabricmc.filament.task.mappingio.CompleteMappingsTask;
import net.fabricmc.filament.task.mappingio.ConvertMappingsTask;
import net.fabricmc.filament.task.mappingio.MergeMappingsTask;
import net.fabricmc.filament.task.minecraft.ExtractBundledServerTask;
import net.fabricmc.filament.task.minecraft.MergeMinecraftTask;
import net.fabricmc.mappingio.format.MappingFormat;
import net.legacyfabric.multifilament.provider.IntermediaryProvider;
import net.legacyfabric.multifilament.provider.ProviderHandler;
import net.legacyfabric.multifilament.task.*;
import net.legacyfabric.multifilament.util.VersionHelper;
import org.gradle.api.Action;
import org.gradle.api.Project;
import org.gradle.api.artifacts.Configuration;
import org.gradle.api.file.Directory;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.file.RegularFile;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.java.archives.Manifest;
import org.gradle.api.provider.Property;
import org.gradle.api.provider.Provider;
import org.gradle.api.tasks.bundling.Jar;

import javax.inject.Inject;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.zip.GZIPOutputStream;

public abstract class MultiFilamentExtension {

    private DownloadTask downloadIntermediary;
    private VersionifyFilterMappingsTask versionifyMappingsFilter;
    private VersionifyExcludeMappingsTask versionifyMappingsExclude;
    private DeduplicateMappingsTask deduplicateMappings;
    private UnifyMappingsTask unifyMappings;
    private UnifyMappingsTask unifyMappingsFix;
    private MergeMinecraftTask mergeOriginalJars;
    private MapJarTask mapIntermediaryJar;
    private MapJarTask mapServerIntermediaryJar;
    private MapSpecializedMethodsTask mapSpecializedMethods;
    private CompleteMappingsTask completeMappings;
    private ConvertMappingsTask convertToV1;
    private MergeMappingsTask mergeTiny;
    private Action<Manifest> manifestAction;
    private Jar tinyJar;
    private FileInputOutput compressTiny;
//    private Task checkMappings;
    private CombineUnpickDefinitionsTask combineUnpickDefinitions;
//    private FileInputOutput insertAutoGeneratedEnumMappings;
//    private FixedRemapUnpickDefinitionsTask fixedRemapUnpickDefinitionsIntermediary;
//    private MergeMappingsTask mergeV2;

    public static MultiFilamentExtension get(Project project) {
        return project.getExtensions().getByType(MultiFilamentExtension.class);
    }

    @Inject
    protected abstract Project getProject();

    public abstract DirectoryProperty getTempDirectory();
    public abstract DirectoryProperty getLibsDirectory();
    public abstract DirectoryProperty getCacheDirectory();

    public abstract Property<Integer> getIntermediaryRevision();
    public abstract DirectoryProperty getActiveMappingsDir();
    public abstract DirectoryProperty getMultiMappingsDir();
    public abstract DirectoryProperty getTempMappingsDir();
    public abstract Property<String> getYarnGroup();
    public abstract Property<String> getBuildMappingGroup();
    public abstract Property<String> getMapJarGroupGroup();
    public abstract Property<String> getVersion();
    public abstract DirectoryProperty getUnpickDefinitionsDir();
    public abstract RegularFileProperty getUnpickMetaFile();
    public abstract Property<String> getUnpickVersion();

    private IntermediaryProvider intermediaryProvider;
    private final Property<String> minecraftVersion;

    private Configuration
            asm,
            enigmaRuntime,
            javadocClasspath,
            decompileClasspath,
            mappingPoetJar,
            mappingPoet
                    ;

    @Inject
    public MultiFilamentExtension() {
        getTempDirectory().set(getProject().getObjects().directoryProperty().fileValue(new File(getProject().getRootDir(), "build/temp/yarn")));
        getLibsDirectory().set(getProject().getObjects().directoryProperty().fileValue(new File(getProject().getRootDir(), "build/libs")));
        getCacheDirectory().set(getProject().getObjects().directoryProperty().fileValue(new File(getProject().getRootDir(), ".gradle/multi-filament")));

        minecraftVersion = FilamentExtension.get(getProject()).getMinecraftVersion();
        getIntermediaryRevision().finalizeValueOnRead();
        getActiveMappingsDir().finalizeValueOnRead();
        getMultiMappingsDir().finalizeValueOnRead();
        getYarnGroup().finalizeValueOnRead();
        getBuildMappingGroup().finalizeValueOnRead();
        getMapJarGroupGroup().finalizeValueOnRead();
        getVersion().finalizeValueOnRead();
        getUnpickDefinitionsDir().finalizeValueOnRead();
        getUnpickMetaFile().finalizeValueOnRead();
        getUnpickVersion().finalizeValueOnRead();
    }

    protected void createConfigurations() {
        asm = getProject().getConfigurations().create("asm");
        enigmaRuntime = getProject().getConfigurations().create("enigmaRuntime", conf -> {
            conf.extendsFrom(asm);
        });
        javadocClasspath = getProject().getConfigurations().create("javadocClasspath");
        decompileClasspath = getProject().getConfigurations().create("decompileClasspath");
        mappingPoetJar = getProject().getConfigurations().create("mappingPoetJar", conf -> {
            conf.setTransitive(false);
        });
        mappingPoet = getProject().getConfigurations().create("mappingPoet", conf -> {
            conf.extendsFrom(mappingPoetJar, asm);
            conf.setTransitive(true);
        });
    }

    protected void createTasks() {
        downloadIntermediary = getProject().getTasks().create("downloadIntermediary", DownloadTask.class, downloadTask -> {
//            downloadTask.setGroup(getBuildMappingGroup().get());
            downloadTask.setGroup("mapping build");
            downloadTask.getUrl().set(
                    minecraftVersionGetter().map(v -> getIntermediaryProvider().getIntermediaryURL(v))
            );
            downloadTask.getOutput().set(getMinecraftCacheDirectory().flatMap(
                    dir -> minecraftVersionGetter().map(v -> dir.file(v + "-intermediary.tiny")))
            );
        });

        versionifyMappingsFilter = getProject().getTasks().create("versionifyMappingsFilter", VersionifyFilterMappingsTask.class, task -> {
            task.dependsOn(downloadIntermediary);
            task.getIntermediaryFile().set(downloadIntermediary.getOutputFile());
            task.getInputDir().set(getMultiMappingsDir());
            task.getOutputDir().set(getActiveMappingsDir());
            task.getOutputs().upToDateWhen(c -> false);
        });

        versionifyMappingsExclude = getProject().getTasks().create("versionifyMappingsExclude", VersionifyExcludeMappingsTask.class, task -> {
            task.dependsOn(downloadIntermediary, versionifyMappingsFilter);
            task.getIntermediaryFile().set(downloadIntermediary.getOutputFile());
            task.getInputDir().set(getMultiMappingsDir());
            task.getOutputDir().set(getTempMappingsDir());
            task.getOutputs().upToDateWhen(c -> false);
        });

        deduplicateMappings = getProject().getTasks().create("deduplicateMappings", DeduplicateMappingsTask.class, task -> {
            task.getInputDir().set(getMultiMappingsDir());
            task.getOutputDir().set(getTempMappingsDir());
        });

        unifyMappings = getProject().getTasks().create("unifyMappings", UnifyMappingsTask.class, task -> {
            task.dependsOn(versionifyMappingsExclude);
            task.getUnifiedDir().set(getTempMappingsDir());
            task.getVersionedDir().set(getActiveMappingsDir());
            task.getOutputDir().set(getMultiMappingsDir());
            task.getOutputs().upToDateWhen(c -> false);
        });

        unifyMappingsFix = getProject().getTasks().create("unifyMappingsFix", UnifyMappingsTask.class, task -> {
            task.getUnifiedDir().set(getTempMappingsDir());
            task.getVersionedDir().set(getActiveMappingsDir());
            task.getOutputDir().set(getMultiMappingsDir());
            task.getOutputs().upToDateWhen(c -> false);
        });

        mergeOriginalJars = getProject().getTasks().create("mergeOriginalMinecraftJars", MergeMinecraftTask.class, task -> {
            DownloadTask clientJar = (DownloadTask) getProject().getTasks().getByName("downloadMinecraftClientJar");
            DownloadTask serverJar = (DownloadTask) getProject().getTasks().getByName("downloadMinecraftServerJar");

            task.dependsOn(clientJar, serverJar);
            task.getClientJar().set(clientJar.getOutput());
            task.getServerJar().set(serverJar.getOutput());

            task.getOutput().set(FilamentExtension.get(getProject()).getMinecraftFile("merged.jar"));
        });

        mapIntermediaryJar = getProject().getTasks().create("mapIntermediaryJar", MapJarTask.class, task -> {
            MergeMinecraftTask mergeJars = (MergeMinecraftTask) getProject().getTasks().getByName("mergeMinecraftJars");

            task.dependsOn(isServerBundled() ? mergeJars : mergeOriginalJars);
//            task.setGroup(getMapJarGroupGroup().get());
            task.setGroup("jar mappings");
            task.getOutput().set(minecraftVersionGetter().flatMap(v -> getCacheFile(v + "-intermediary.jar")));
            task.getInput().set(isServerBundled() ? mergeJars.getOutput() : mergeOriginalJars.getOutput());
            task.getMappings().set(downloadIntermediary.getOutput());
            task.getClasspath().from(getMinecraftLibsConfiguration());
            task.getFrom().set("official");
            task.getTo().set("intermediary");
        });

        mapServerIntermediaryJar = getProject().getTasks().create("mapServerIntermediaryJar", MapJarTask.class, task -> {
            ExtractBundledServerTask extractBundledServer = (ExtractBundledServerTask) getProject().getTasks().getByName("extractBundledServer");
            DownloadTask serverJar = (DownloadTask) getProject().getTasks().getByName("downloadMinecraftServerJar");

            task.dependsOn(isServerBundled() ? extractBundledServer : serverJar);
//            task.setGroup(getMapJarGroupGroup().get());
            task.setGroup("jar mappings");
            task.getOutput().set(minecraftVersionGetter().flatMap(v -> getCacheFile(v + "-server-intermediary.jar")));
            task.getInput().set(isServerBundled() ? extractBundledServer.getOutput() : serverJar.getOutput());
            task.getMappings().set(downloadIntermediary.getOutput());
            task.getClasspath().from(getMinecraftLibsConfiguration());
            task.getFrom().set("official");
            task.getTo().set("intermediary");
        });

        mapSpecializedMethods = getProject().getTasks().create("mapSpecializedMethods", MapSpecializedMethodsTask.class, task -> {
            task.dependsOn(versionifyMappingsExclude);
            task.getIntermediaryJarFile().set(mapIntermediaryJar.getOutput());
            task.getMappings().set(getActiveMappingsDir());
            task.getOutput().set(getTempDirectory().file("yarn-specialized-mappings-v2.tiny"));

            task.getInputMappingsFormat().set("enigma");
            task.getOutputMappingsFormat().set("tinyv2:intermediary:named");
        });

        completeMappings = getProject().getTasks().create("completeMappings", CompleteMappingsTask.class, task -> {
            task.getInput().set(mapSpecializedMethods.getOutput());
            task.getOutput().set(getTempDirectory().file("yarn-mappings-v2.tiny"));
            task.getOutputFormat().set(MappingFormat.TINY_2_FILE);
        });

        convertToV1 = getProject().getTasks().create("convertToV1", ConvertMappingsTask.class, task -> {
            task.getInput().set(mapSpecializedMethods.getOutput());
            task.getOutput().set(getTempDirectory().file("yarn-mappings.tiny"));
            task.getOutputFormat().set(MappingFormat.TINY_FILE);
        });

        mergeTiny = getProject().getTasks().create("mergeTiny", MergeMappingsTask.class, task -> {
//            task.setGroup(getBuildMappingGroup().get());
            task.setGroup("mapping build");
            task.getOutput().set(getTempDirectory().file("mappings.tiny"));
            task.getMappingInputs().from(downloadIntermediary.getOutput());
            task.getMappingInputs().from(convertToV1.getOutput());
            task.getOutputFormat().set(MappingFormat.TINY_FILE);
        });

        manifestAction = manifest -> {
            manifest.getAttributes().put("Minecraft-Version-Id", minecraftVersionGetter().get());
//            manifest.getAttributes().put("Intermediary-Version", getIntermediaryRevision().get());
        };

        tinyJar = getProject().getTasks().create("tinyJar", Jar.class, task -> {
            task.dependsOn(mergeTiny);
//            task.setGroup(getBuildMappingGroup().get());
            task.setGroup("mapping build");
            task.getArchiveFileName().set(getVersion().map(v -> "yarn-" + v + ".jar"));
            task.getDestinationDirectory().set(getLibsDirectory());
            task.getArchiveClassifier().set("");

            task.from(mergeTiny.getOutput(), from -> {
                from.rename(s -> "mappings/mappings.tiny");
            });

            task.manifest(manifestAction);
        });

        compressTiny = getProject().getTasks().create("compressTiny", FileInputOutput.class, task -> {
            task.dependsOn(tinyJar, mergeTiny);
//            task.setGroup(getBuildMappingGroup().get());
            task.setGroup("mapping build");

            task.getInput().set(mergeTiny.getOutput());
            task.getOutput().set(getVersion().flatMap(v -> getLibsDirectory().file("yarn-tiny-" + v + ".gz")));

            task.doLast(currentTaskGradle -> {
                try {
                    FileInputOutput currentTask = (FileInputOutput) currentTaskGradle;
                    var buffer = new byte[1024];
                    var fileOutputStream = new FileOutputStream(currentTask.getOutputFile());
                    var outputStream = new GZIPOutputStream(fileOutputStream);
                    var fileInputStream = new FileInputStream(currentTask.getInputFile());

                    int length;
                    while ((length = fileInputStream.read(buffer)) > 0) {
                        outputStream.write(buffer, 0, length);
                    }

                    fileInputStream.close();
                    outputStream.finish();
                    outputStream.close();
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            });
        });

//        checkMappings = getProject().getTasks().create("checkMappings", task -> {
//            task.dependsOn(versionifyMappingsExclude);
////            task.setGroup(getBuildMappingGroup().get());
//            task.setGroup("mapping build");
//            task.getInputs().dir(getActiveMappingsDir());
//            task.getInputs().file(mapIntermediaryJar.getOutput());
//
//            task.doLast(currentTask -> {
//                String[] args = new String[] {
//                        mapIntermediaryJar.getOutputFile().getAbsolutePath(),
//                        getActiveMappingsDir().getAsFile().get().getAbsolutePath()
//                };
//
//                try {
//                    new CheckMappingsCommand().run(args);
//                } catch (Exception ignored) {
//                    // just print, don't fail the task
//                }
//            });
//        });

        combineUnpickDefinitions = (CombineUnpickDefinitionsTask) getProject().getTasks().getByName("combineUnpickDefinitions", gradleTask -> {
            CombineUnpickDefinitionsTask task = (CombineUnpickDefinitionsTask) gradleTask;
            task.setGroup("unpick");
            task.getInput().set(getUnpickDefinitionsDir());
            task.getOutput().set(getTempDirectory().file("definitions.unpick"));
        });

//        insertAutoGeneratedEnumMappings = getProject().getTasks().create("insertAutoGeneratedEnumMappings", FileInputOutput.class, task -> {
//            task.dependsOn(mapIntermediaryJar, downloadIntermediary);
////            task.setGroup(getBuildMappingGroup().get());
//            task.setGroup("mapping build");
//            task.getInput().set(completeMappings.getOutput());
//            task.getOutput().set(getTempDirectory().file("unmerged-named-v2-with-enum.tiny"));
//
//            task.getInputs().file(mapIntermediaryJar.getOutput());
//            task.getInputs().file(downloadIntermediary.getOutput());
//
//            task.doLast(currentTaskGradle -> {
//                FileInputOutput currentTask = (FileInputOutput) currentTaskGradle;
//
//                try {
//                    MappingNameCompleter.completeNames(
//                            mapIntermediaryJar.getOutputPath(),
//                            currentTask.getInputPath(),
//                            downloadIntermediary.getOutputPath(),
//                            currentTask.getOutputPath()
//                    );
//                } catch (IOException e) {
//                    throw new RuntimeException(e);
//                }
//            });
//        });

//        fixedRemapUnpickDefinitionsIntermediary = getProject().getTasks().create("fixedRemapUnpickDefinitionsIntermediary", FixedRemapUnpickDefinitionsTask.class, task -> {
//            task.setGroup("unpick");
//            task.dependsOn(combineUnpickDefinitions);
//            task.getInput().set(combineUnpickDefinitions.getOutput());
//            task.getSourceNamespace().set("named");
//            task.getTargetNamespace().set("intermediary");
//
//            task.getOutput().set(getTempDirectory().file("intermediary-definitions.unpick"));
//            task.getMappings().set(insertAutoGeneratedEnumMappings.getOutput());
//        });

//        mergeV2 = getProject().getTasks().create("mergeV2", MergeMappingsTask.class, task -> {
////            task.setGroup(getBuildMappingGroup().get());
//            task.setGroup("mapping build");
//            task.getOutput().set(getTempDirectory().file("merged-v2.tiny"));
//            task.getMappingInputs().from(downloadIntermediary.getOutput());
//            task.getMappingInputs().from(insertAutoGeneratedEnumMappings.getOutput());
//            task.getOutputFormat().set(MappingFormat.TINY_2_FILE);
//        });
    }

    protected void createTasksLate() {
//        UnpickJarTask unpickIntermediaryJar = getProject().getTasks().create("unpickIntermediaryJar", UnpickJarTask.class, task -> {
//            Jar constantsJar = (Jar) getProject().getTasks().getByName("constantsJar");
//
//            task.setGroup("unpick");
//            task.getInput().set(mapIntermediaryJar.getOutput());
//            task.getOutput().set(minecraftVersionGetter().flatMap(v -> getCacheFile(v + "-intermediary-unpicked.jar")));
//            task.getUnpickDefinition().set(fixedRemapUnpickDefinitionsIntermediary.getOutput());
//            task.getConstantsJarFile().set(constantsJar.getArchiveFile());
//            task.getClasspath().from(getMinecraftLibsConfiguration());
//        });

        Jar v2UnmergedYarnJar = getProject().getTasks().create("v2UnmergedYarnJar", Jar.class, task -> {
            FileInputOutput insertAutoGeneratedEnumMappings = (FileInputOutput) getProject().getTasks().getByName("insertAutoGeneratedEnumMappings");

            yarnV2Jar(
                    task,
                    getVersion().map(v -> "yarn-" + v + "-v2.jar"),
                    insertAutoGeneratedEnumMappings.getOutput(),
                    combineUnpickDefinitions.getOutput(),
                    manifestAction,

                    insertAutoGeneratedEnumMappings, combineUnpickDefinitions
            );
        });

        Jar v2MergedYarnJar = getProject().getTasks().create("v2MergedYarnJar", Jar.class, task -> {
            MergeMappingsTask mergeV2 = (MergeMappingsTask) getProject().getTasks().getByName("mergeV2");

            yarnV2Jar(
                    task,
                    getVersion().map(v -> "yarn-" + v + "-mergedv2.jar"),
                    mergeV2.getOutput(),
                    combineUnpickDefinitions.getOutput(),
                    manifestAction,

                    mergeV2
            );
        });
    }

    private void yarnV2Jar(Jar task, Provider<String> fileName, RegularFileProperty mappings, RegularFileProperty unpickDefinitions, Action<Manifest> manifestAction, Object... dependsOn) {
        task.dependsOn(dependsOn);
//            task.setGroup(getBuildMappingGroup().get());
        task.setGroup("mapping build");

        task.getArchiveFileName().set(fileName);

        task.from(mappings, from -> {
            from.rename(mappings.get().getAsFile().getName(), "mappings/mappings.tiny");
        });

        task.from(unpickDefinitions, from -> {
            from.rename(unpickDefinitions.get().getAsFile().getName(), "extras/definitions.unpick");
        });

        task.from(getUnpickMetaFile(), from -> {
            from.expand(new HashMap<>(Map.of("version", getUnpickVersion().get())));
            from.rename(getUnpickMetaFile().get().getAsFile().getName(), "extras/unpick.json");
        });

        task.getDestinationDirectory().set(getLibsDirectory());

        task.manifest(manifestAction);
    }

    private Property<String> minecraftVersionGetter() {
        return minecraftVersion;
    }

    public IntermediaryProvider getIntermediaryProvider() {
        if (intermediaryProvider == null) {
            intermediaryProvider = ProviderHandler.get(minecraftVersionGetter().get(), getIntermediaryRevision().get());
        }

        return intermediaryProvider;
    }

    public Provider<Directory> getMinecraftCacheDirectory() {
        return getTempDirectory().dir("minecraft");
    }

    public Provider<Directory> getIntermediaryRevisionDirectory() {
        return getCacheDirectory().dir(getIntermediaryRevision().map(r -> "v" + r));
    }

    public Provider<RegularFile> getCacheFile(String filename) {
        return getIntermediaryRevisionDirectory().map(directory -> directory.file(filename));
    }

    private Configuration getMinecraftLibsConfiguration() {
        return getProject().getConfigurations().getByName("minecraftLibraries");
    }

    public boolean isServerBundled() {
        return VersionHelper.isServerBundled(minecraftVersionGetter().get());
    }
}
