name: Release
on: [workflow_dispatch] # Manual trigger
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:20-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - run: ./gradlew build publish --stacktrace --no-configuration-cache
        env:
          MAVEN_PUBLISH_CREDENTIALS: ${{ secrets.MAVEN_PUBLISH_CREDENTIALS }}